name: dcn
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - charset-normalizer=2.0.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=1.26.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - pycparser=2.21
  - python=3.11.0
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtriton=2.1.0
  - typing_extensions=4.9.0
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - brotli==1.0.9
    - certifi==2023.11.17
    - cffi==1.16.0
    - cryptography==41.0.3
    - filelock==3.13.1
    - gmpy2==2.1.2
    - idna==3.4
    - jinja2==3.1.2
    - markupsafe==2.1.3
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.26.3
    - pandas==2.1.4
    - pillow==10.0.1
    - pip==23.3.1
    - pyopenssl==23.2.0
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests==2.31.0
    - setuptools==68.2.2
    - six==1.16.0
    - sympy==1.12
    - torch==2.1.1
    - torchaudio==2.1.1
    - torchvision==0.16.1
    - triton==2.1.0
    - typing-extensions==4.9.0
    - tzdata==2023.4
    - urllib3==1.26.18
    - wheel==0.41.2

